import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
 <html lang="fr">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col bg-slate-50 text-slate-900`}>
        {/* Navbar présente partout */}
        <Navbar />

        {/* Contenu principal dynamique */}
        <main className="grow">
          {children}
        </main>

        {/* Footer simple demandé par le brief */}
        <footer className="bg-slate-950 text-gray-400 text-center py-4 border-t border-slate-800 text-sm">
          <p>© {new Date().getFullYear()} - Hanine Ayoub - </p>
        </footer>
      </body>
    </html>
  );
}
